name: 'Build and Push Images'
description: 'Build and Push Images'
author: 'Ops'
inputs:
  aws-region:
    description: 'AWS Region'
    required: true
    default: 'us-east-1'
  aws-account-id:
    description: 'AWS Account ID, default to SVV hub'
    required: false
    default: '925998874146'
runs:
  using: 'composite'
  steps:
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login ECR
      uses: jwstric2/workflows/.github/actions/login-ecr@feature/more_stuff
      with:
        aws-region: ${{ inputs.aws-region }}
        aws-account-id: ${{ inputs.aws-account-id }}
        write-access: false
