name: 'Login to ECR'
description: 'Login to ECR public and private repositories'
author: 'Ops'
inputs:
  aws-region:
    description: 'AWS Region'
    required: true
    default: 'us-east-1'
  aws-account-id:
    description: 'AWS Account ID, default to SVV hub'
    required: false
    default: '925998874146'
  write-access:
    description: 'Write Access to Private ECR repositories'
    required: false
    default: 'false'
outputs:
  private-ecr-registry:
    description: "Private registry"
    value: ${{ steps.set-endpoints.outputs.private-ecr-registry }}
  public-ecr-registry:
    description: "Public registry"
    value: ${{ steps.set-endpoints.outputs.public-ecr-registry }} 

runs:
  using: 'composite'
  steps:
    - name: Set endpoints
      id: set-endpoints
      run: |
        echo private-ecr-registry=$(echo ${{ inputs.aws-account-id }}.dkr.ecr.${{ inputs.aws-region }}.amazonaws.com) >> $GITHUB_OUTPUT"
        echo public-ecr-registry=$(echo public.ecr.aws) >> $GITHUB_OUTPUT"
      shell: bash
    - name: Set the account role to assume
      id: set-account-role
      run: |
        if [ "${{ inputs.write-access }}" == "true" ]; then
          echo ROLE_NAME=$(echo GHA_${GITHUB_REPOSITORY%/*}_WRITER) >> $GITHUB_ENV
        else
          echo ROLE_NAME=$(echo GHA_${GITHUB_REPOSITORY%/*}_READER) >> $GITHUB_ENV
        fi
      shell: bash
    - name: configure aws credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-region: ${{ inputs.aws-region }}
        retry-max-attempts: 3
        role-to-assume: arn:aws:iam::${{ inputs.aws-account-id }}:role/${{ env.ROLE_NAME }}
        role-session-name: GH_to_AWS_via_FederatedOIDC_${{ env.ROLE_NAME }}
    - name: Sts GetCallerIdentity
      run: |
        aws sts get-caller-identity
      shell: bash
    - name: Login Private AWS ECR
      run: |
        aws ecr get-login-password \
        | docker login --username AWS --password-stdin \
            ${{ steps.set-endpoints.outputs.private-ecr-registry }}
      shell: bash
    - name: Login Public AWS ECR
      run: |
        aws ecr-public get-login-password \
        | docker login --username AWS --password-stdin \
            ${{ steps.set-endpoints.outputs.public-ecr-registry }}
      shell: bash