name: 'Login to ECR'
description: 'Login to ECR public and private repositories'
author: 'Ops'
inputs:
  aws-region:
    description: 'AWS Region'
    required: true
    default: 'us-east-1'
  aws-account-id:
    description: 'AWS Account ID, default to SVV hub'
    required: false
    default: '925998874146'
  write-access:
    description: 'Write Access to Private ECR repositories'
    required: false
    default: 'false'

runs:
  using: 'composite'
  steps:
    - name: Set the account role to assume
      id: set-account-role
      run: |
        if [ "${{ inputs.write-access }}" == "true" ]; then
          echo PRIVATE_ROLE_NAME=$(echo GHA_${GITHUB_REPOSITORY%/*}_WRITER) >> $GITHUB_ENV
        else
          echo PRIVATE_ROLE_NAME=$(echo GHA_${GITHUB_REPOSITORY%/*}_READER) >> $GITHUB_ENV
        fi
      shell: bash
    - name: configure aws credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-region: ${{ inputs.aws-region }}
        retry-max-attempts: 3
        role-to-assume: arn:aws:iam::${{ inputs.aws-account-id }}:role/${{ env.PRIVATE_ROLE_NAME }}
        role-session-name: GH_to_AWS_via_FederatedOIDC_${{ env.ROLE-NAME }}
    - name: Sts GetCallerIdentity
      run: |
        aws sts get-caller-identity
      shell: bash
    - name: Login AWS ECR
      run: |
        aws ecr get-login-password \
        | docker login --username AWS --password-stdin \
            ${{ inputs.aws-account-id }}.dkr.ecr.${{ inputs.aws-region }}.amazonaws.com
      shell: bash