name: ci

on:
  pull_request:

permissions:
  contents: read
  pull-requests: read

jobs:
  lint:
    if: ${{ github.event_name == 'pull_request' }}
    uses: ./.github/workflows/lint-pr.yml
  ci:
    runs-on: ubuntu-latest
    needs: [lint]
    steps:
      - name: Depending job on other workflows to create an enforcing org ci / ci status check
        run: |
          echo "Complete"