name: Ruby Gem Release

on:
    workflow_call:
      inputs:
        ruby-version:
          description: Ruby Version to Build The Gem With
          default: '3.1'
          required: true
          type: string
        version-file:
          description: Ruby Version File Path To Update
          required: true
          type: string

jobs:
  release-please:
    runs-on: ubuntu-latest
      
    steps:
      - id: create_token
        uses: tibdex/github-app-token@v2
        with:
          app_id: ${{ secrets.RELEASE_POLICE_APP_ID }}
          private_key: ${{ secrets.RELEASE_POLICE_APP_PRIVATE_KEY }}

      # Uses release-please-action    
      - uses: google-github-actions/release-please-action@v3
        id: release
        with:
          # Personal Access Token.  We do not use the default token action app token as
          # it will upon creating the branch not allow the ci jobs to be kicked off
          # See https://docs.github.com/en/actions/security-guides/automatic-token-authentication#using-the-github_token-in-a-workflow
          token: ${{ steps.create_token.outputs.token }}
          
          # Use https://github.com/googleapis/release-please/blob/main/src/strategies/ruby.ts Release Type.
          # This is a ruby type
          release-type: ruby
          
          # Location of the version.rb file to bump for new releases.
          version-file: ${{ inputs.version-file }}

      # Checkout the Repository if a release has been created.  
      - uses: actions/checkout@v2
        if: ${{ steps.release.outputs.release_created }}
      
      # Set up Ruby if a release can be created.
      - uses: ruby/setup-ruby@v1
        with:
          # Latest ruby version (remove to use .ruby-version).
          ruby-version: ${{ inputs.ruby-version }}
        if: ${{ steps.release.outputs.release_created }}

      - name: Publish to Github Packages        
        run: |
          mkdir -p $HOME/.gem
          touch $HOME/.gem/credentials
          chmod 0600 $HOME/.gem/credentials
          printf -- "---\n:github: ${GEM_HOST_API_KEY}\n" > $HOME/.gem/credentials
          gem build *.gemspec
          gem push --KEY github --host https://rubygems.pkg.github.com/${OWNER} *.gem
        env:
          GEM_HOST_API_KEY: "Bearer ${{secrets.GITHUB_TOKEN}}"
          OWNER: ${{ github.repository_owner }}
        if: ${{ steps.release.outputs.release_created }}
